//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zemsaniaTEST.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_DEPARTAMENTO()
        {
            this.HR_PAGO = new HashSet<HR_PAGO>();
        }
    
        public string COD_EMPRESA { get; set; }
        public string COD_DEPARTAMENTO { get; set; }
        public string NOMBRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_PAGO> HR_PAGO { get; set; }
    }
}
