//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zemsaniaTEST.WCF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ZSDBEntities : DbContext
    {
        public ZSDBEntities()
            : base("name=ZSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_DEPARTAMENTO> HR_DEPARTAMENTO { get; set; }
        public virtual DbSet<HR_PAGO> HR_PAGO { get; set; }
    
        public virtual int ProcedureZS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcedureZS");
        }
    }
}
